#!/usr/bin/env python3
r"""run.py - fpga-ip manifest runner.

Resolves the selected .f manifest for an IP, filters the sources by the tool
profile from tool_capabilities.ini, and dispatches to an EDA backend. The
ModelSim/Questa backend writes a flat, reusable Tcl script into <ip>/scripts/
and launches vsim.

Running the axis_fifo VHDL simulation (ModelSim, GUI) -- three ways:

  1. Via this runner, from the fpga-ip repo root:
       run axis_fifo vhdl modelsim gui

  2. Directly from the IP scripts directory (script generated by method 1):
       cd axis_fifo/scripts
       vsim -do sim_vhdl_msim_default_gui.tcl

  3. Directly from the IP sim directory (same script, relative path):
       cd axis_fifo/sim
       vsim -do ..\scripts\sim_vhdl_msim_default_gui.tcl

Project mode creates a native ModelSim/Questa project (.mpf) in
<ip>/sim_proj/ and opens the GUI (the non-project <ip>/sim/ is untouched):

       run axis_fifo vhdl modelsim project

run.py copies the global %MODELSIM% ini to a writable local modelsim.ini in
<ip>/sim_proj/ and clears %MODELSIM% before launching vsim, so the .mpf can
be saved (see fpga-rules/questa_modelsim_project_guide.md).

Vivado XSim simulation (Vivado's built-in simulator), batch and GUI, builds
into <ip>/xsim/. run.py compiles (xvhdl/xvlog) and elaborates (xelab) - XSim
needs one VHDL standard per work library, so all VHDL is compiled at the
manifest DEFAULT_STD - then runs via a generated .tcl (batch) or the GUI:

       run axis_fifo vhdl xsim batch
       run axis_fifo vhdl xsim gui

Vivado synthesis: batch runs non-project synthesis headless in <ip>/vivado/;
gui loads the design in non-project mode and leaves the Vivado GUI open;
project creates a native .xpr project (design + testbench sources) in
<ip>/vivado_proj/ and opens the GUI:

       run axis_fifo vhdl vivado batch
       run axis_fifo vhdl vivado gui
       run axis_fifo vhdl vivado project

Remove build artifacts for an IP (deletes <ip>/sim/, <ip>/sim_proj/,
<ip>/xsim/, <ip>/vivado/, and <ip>/vivado_proj/):
       run clean <ip>

The generated script is self-locating: it derives the repo root from its own
launch directory and changes into <ip>/sim/ itself, so methods 2 and 3 need
no Python and keep all build artifacts under <ip>/sim/.

Spec: common/doc/run-py.md and common/doc/f-format.md
"""

from __future__ import annotations

import argparse
import configparser
import os
import re
import shutil
import subprocess
import sys
from dataclasses import dataclass, field
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent
INI_PATH = REPO_ROOT / "tool_capabilities.ini"

VALID_STDS = {"1993", "2002", "2008", "2019"}
VALID_MODES = ("batch", "gui", "project")
RESERVED_SECTIONS = {"rtl", "top"}

# ---------------------------------------------------------------------------
# Colored output (ANSI). Disabled when output is not a terminal or when
# NO_COLOR is set. On Windows, a no-op system call enables VT processing.
# ---------------------------------------------------------------------------

_USE_COLOR = sys.stdout.isatty() and not os.environ.get("NO_COLOR")
if _USE_COLOR and os.name == "nt":
    os.system("")  # enable ANSI VT processing in the Windows console

GREEN = "\033[32m" if _USE_COLOR else ""
RED = "\033[31m" if _USE_COLOR else ""
YELLOW = "\033[33m" if _USE_COLOR else ""
RESET = "\033[0m" if _USE_COLOR else ""

# A metadata line is "identifier = value". A file path never has '=' in its
# first token, so this is unambiguous (paths contain '/', '.', or are bare
# filenames with no '=').
META_RE = re.compile(r"^([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*)$")


class RunnerError(Exception):
    """Fatal runner error with a user-facing message."""


# ---------------------------------------------------------------------------
# Feature token helpers
# ---------------------------------------------------------------------------

def parse_feature_tokens(value: str) -> list[tuple[str, str]]:
    """Parse a comma-separated feature list into (op, name) tuples.

    A bare token is treated as '+token'. An empty value yields no tokens.
    """
    tokens = []
    for raw in value.split(","):
        tok = raw.strip()
        if not tok:
            continue
        if tok[0] in "+-":
            op, name = tok[0], tok[1:].strip()
        else:
            op, name = "+", tok
        tokens.append((op, name))
    return tokens


# ---------------------------------------------------------------------------
# Capabilities (.ini) loader
# ---------------------------------------------------------------------------

@dataclass
class Capabilities:
    allowed: set[str]
    default_features: set[str]
    sections: list[str]          # section names in INI file order
    data: "configparser.ConfigParser"

    @classmethod
    def load(cls, path: Path) -> "Capabilities":
        if not path.is_file():
            raise RunnerError(f"capability file not found: {path}")
        cfg = configparser.ConfigParser(strict=True)
        cfg.read(path, encoding="utf-8-sig")

        sections = cfg.sections()
        if len(sections) < 2 or sections[0] != "features" or sections[1] != "defaults":
            raise RunnerError(
                "tool_capabilities.ini must start with [features] then [defaults]"
            )
        if "allowed_features" not in cfg["features"]:
            raise RunnerError("[features] missing allowed_features")
        allowed = {t[1] for t in parse_feature_tokens(cfg["features"]["allowed_features"])}
        default_features = {t[1] for t in parse_feature_tokens(cfg["defaults"].get("features", ""))}
        return cls(allowed=allowed, default_features=default_features,
                   sections=sections, data=cfg)

    def has_tool(self, tool: str) -> bool:
        return f"tool.{tool}" in self.data

    def profile_modes(self, tool: str) -> list[str]:
        """Return modes from the matching name-level profile, if declared."""
        for name in self.matching_profiles(tool, None, None):
            modes = self.data[name].get("modes", "")
            if modes:
                return [m.strip() for m in modes.split(",") if m.strip()]
        return []

    def matching_profiles(self, tool: str, version: str | None,
                          edition: str | None) -> list[str]:
        """Profiles that match the identity, in INI file order (never split keys).

        Whole-key matching per spec section 7.2:
          [tool.<name>]
          [tool.<name>.<version>]
          [tool.<name>.<edition>]
          [tool.<name>.<version>.<edition>]
        """
        candidates = []
        if edition is not None:
            if version is not None:
                candidates.append(f"tool.{tool}.{version}.{edition}")
            candidates.append(f"tool.{tool}.{edition}")
        if version is not None:
            candidates.append(f"tool.{tool}.{version}")
        candidates.append(f"tool.{tool}")

        out = []
        for name in self.sections:
            if name in candidates:
                out.append(name)
        return out

    def effective_features(self, tool: str, version: str | None,
                           edition: str | None) -> set[str]:
        """Apply matching profiles top-to-bottom over the [defaults] baseline."""
        features = set(self.default_features)
        for name in self.matching_profiles(tool, version, edition):
            for op, feat in parse_feature_tokens(self.data[name].get("features", "")):
                if op == "+":
                    features.add(feat)
                else:
                    features.discard(feat)
        return features


# ---------------------------------------------------------------------------
# Manifest (.f) parser
# ---------------------------------------------------------------------------

@dataclass
class FileEntry:
    path: Path                 # absolute path
    section: str               # originating section (for reporting)
    std: str | None            # effective std (None for non-VHDL / unset)
    lib: str                   # effective library
    tools: list[str]           # allow-list from tool= (empty = all tools)
    order: int                 # sequence number in the closure

    def compile_options(self) -> str:
        opts = []
        if self.std:
            opts.append(f"std={self.std}")
        if self.lib:
            opts.append(f"lib={self.lib}")
        if self.tools:
            opts.append("tool=" + ",".join(self.tools))
        return " ".join(opts) if opts else "-"


@dataclass
class IncludeEntry:
    path: Path                 # absolute path of included manifest
    section_name: str          # section to import
    std_override: str | None   # include-level std= (None = no override)
    order: int


@dataclass
class Section:
    name: str
    entries: list = field(default_factory=list)   # FileEntry | IncludeEntry
    meta: dict = field(default_factory=dict)      # top, time_res, requires, wave


@dataclass
class Manifest:
    path: Path
    directives: dict[str, str]
    sections: dict[str, Section]
    section_order: list[str]

    def default_std(self) -> str:
        return self.directives.get("DEFAULT_STD", "2008")

    def default_lib(self) -> str:
        return self.directives.get("DEFAULT_LIB", "work")


def _parse_attrs(tokens: list[str]) -> dict[str, str]:
    attrs = {}
    for tok in tokens:
        if "=" in tok:
            key, _, value = tok.partition("=")
            attrs[key.strip().lower()] = value.strip()
    return attrs


def _validate_section_name(name: str) -> None:
    if name in RESERVED_SECTIONS:
        return
    if name.startswith("tb:"):
        return
    if name == "tb":
        raise RunnerError("unnamed [tb] section is not supported; use [tb:<name>]")
    if name.startswith("wave:") or name.startswith("constraints:"):
        return
    raise RunnerError(f"unknown section [{name}]")


def parse_manifest(path: Path) -> Manifest:
    """Parse one .f manifest. File paths are relative to the repo root."""
    if not path.is_file():
        raise RunnerError(f"manifest not found: {path}")
    directives: dict[str, str] = {}
    sections: dict[str, Section] = {}
    section_order: list[str] = []
    current: Section | None = None

    for raw in path.read_text(encoding="utf-8-sig").splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue

        if line.startswith("["):
            end = line.find("]")
            if end < 0:
                raise RunnerError(f"malformed section header: {line}")
            name = line[1:end].strip()
            _validate_section_name(name)
            if name in sections:
                raise RunnerError(f"duplicate section [{name}] in {path.name}")
            current = Section(name=name)
            sections[name] = current
            section_order.append(name)
            continue

        if current is None:
            # Global directive: KEY: VALUE
            if ":" not in line:
                raise RunnerError(f"expected directive 'KEY: VALUE' before sections: {line}")
            key, _, value = line.partition(":")
            directives[key.strip().upper()] = value.strip()
            continue

        # Section metadata line: "key = value" (top, time_res, requires, wave,
        # group, signal, ...). File paths never start with 'identifier ='.
        meta = META_RE.match(line)
        if meta:
            current.meta[meta.group(1).lower()] = meta.group(2).strip()
            continue

        # Section entry: file path with attributes, or an include.
        tokens = line.split()
        if tokens[0].lower() == "include":
            if len(tokens) < 2:
                raise RunnerError(f"include without a path: {line}")
            inc_path = Path(tokens[1])
            section_name = None
            attrs = {}
            for tok in tokens[2:]:
                if tok.startswith("[") and tok.endswith("]"):
                    section_name = tok[1:-1]
                elif "=" in tok:
                    attrs.update(_parse_attrs([tok]))
                else:
                    raise RunnerError(f"unexpected include token: {tok}")
            if section_name is None:
                raise RunnerError(f"include missing a [section]: {line}")
            std_override = attrs.get("std")
            if std_override is not None and std_override not in VALID_STDS:
                raise RunnerError(f"invalid include std={std_override} in {path.name}")
            current.entries.append(IncludeEntry(
                path=(REPO_ROOT / inc_path).resolve(),
                section_name=section_name,
                std_override=std_override,
                order=len(current.entries),
            ))
            continue

        attrs = _parse_attrs(tokens[1:])
        entry_path = (REPO_ROOT / tokens[0]).resolve()
        std = attrs.get("std")
        if std is not None and std not in VALID_STDS:
            raise RunnerError(f"invalid std={std} for {tokens[0]}")
        lib = attrs.get("lib")
        tools = [t.strip() for t in attrs.get("tool", "").split(",") if t.strip()]
        current.entries.append(FileEntry(
            path=entry_path,
            section=current.name,
            std=std,
            lib=lib or "",
            tools=tools,
            order=len(current.entries),
        ))

    if not section_order:
        raise RunnerError(f"manifest has no sections: {path.name}")
    return Manifest(path=path, directives=directives,
                    sections=sections, section_order=section_order)


# ---------------------------------------------------------------------------
# Source closure expansion (includes, ordered, cycle-safe)
# ---------------------------------------------------------------------------

def expand_section(manifest: Manifest, section_name: str,
                   forced_std: str | None, counter: list[int],
                   out: list[FileEntry], stack: list[Path],
                   manifest_cache: dict[Path, Manifest]) -> None:
    """Append resolved FileEntry objects for a section, in order.

    forced_std comes from an include-level std= override and, when set, wins
    over the included manifest's DEFAULT_STD and per-entry std= for VHDL files.
    """
    if section_name not in manifest.sections:
        raise RunnerError(f"section [{section_name}] not found in {manifest.path.name}")
    if manifest.path in stack:
        cycle = " -> ".join(str(p) for p in stack + [manifest.path])
        raise RunnerError(f"include cycle detected: {cycle}")

    stack.append(manifest.path)
    try:
        for entry in manifest.sections[section_name].entries:
            if isinstance(entry, IncludeEntry):
                inc = manifest_cache.get(entry.path)
                if inc is None:
                    inc = parse_manifest(entry.path)
                    manifest_cache[entry.path] = inc
                expand_section(inc, entry.section_name, entry.std_override,
                               counter, out, stack, manifest_cache)
            else:
                is_vhdl = entry.path.suffix.lower() in (".vhd", ".vhdl")
                if forced_std is not None and is_vhdl:
                    std = forced_std
                else:
                    std = entry.std or (manifest.default_std() if is_vhdl else None)
                lib = entry.lib or manifest.default_lib()
                if entry.tools:
                    tools = entry.tools
                else:
                    tools = []
                counter[0] += 1
                out.append(FileEntry(
                    path=entry.path, section=entry.section, std=std, lib=lib,
                    tools=tools, order=counter[0],
                ))
    finally:
        stack.pop()


def build_closure(manifest: Manifest, section_names: list[str],
                  tool: str, manifest_cache: dict[Path, Manifest]) -> list[FileEntry]:
    """Build the ordered source closure for the requested sections.

    Files with a tool= allow-list that excludes the selected tool are skipped.
    Existence of the remaining files is checked by the caller so that the full
    listing can be shown with per-file status.
    """
    out: list[FileEntry] = []
    counter = [0]
    for section in section_names:
        expand_section(manifest, section, None, counter, out, [], manifest_cache)
    # Filter by tool allow-list, preserving order.
    filtered = [e for e in out if not e.tools or tool in e.tools]
    skipped = len(out) - len(filtered)
    if skipped:
        print(f"  (skipped {skipped} file(s) by tool= allow-list for '{tool}')")
    return filtered


# ---------------------------------------------------------------------------
# Selection
# ---------------------------------------------------------------------------

def select_testbenches(manifest: Manifest, tb_arg: str | None,
                       tool: str) -> list[str]:
    """Return the list of [tb:<name>] sections to run."""
    tb_sections = [n for n in manifest.section_order if n.startswith("tb:")]

    if tool == "vivado":
        if tb_arg:
            raise RunnerError("vivado synthesis does not accept --tb")
        return []

    if tb_arg is not None:
        if tb_arg == "all":
            if not tb_sections:
                raise RunnerError("--tb all but manifest has no testbench sections")
            return tb_sections
        name = f"tb:{tb_arg}"
        if name not in manifest.sections:
            raise RunnerError(f"testbench [{name}] not found in {manifest.path.name}")
        return [name]

    # No --tb: DEFAULT_TB, else single implicit, else error.
    if "DEFAULT_TB" in manifest.directives:
        default = f"tb:{manifest.directives['DEFAULT_TB']}"
        if default not in manifest.sections:
            raise RunnerError(f"DEFAULT_TB refers to missing [{default}]")
        return [default]
    if len(tb_sections) == 1:
        return tb_sections
    if not tb_sections:
        raise RunnerError("manifest has no testbench section")
    raise RunnerError("multiple testbenches; select one with --tb or set DEFAULT_TB")


def target_sections(manifest: Manifest, tb_name: str | None) -> list[str]:
    """Section list for the requested target in compile order."""
    sections = []
    if "rtl" in manifest.sections:
        sections.append("rtl")
    if tb_name is not None:
        sections.append(tb_name)
    else:
        if "top" in manifest.sections:
            sections.append("top")
        cons = [n for n in manifest.section_order if n.startswith("constraints:")]
        if cons:
            sections.extend(cons)
    return sections


# ---------------------------------------------------------------------------
# ModelSim / Questa backend (batch/gui simulation + native .mpf project mode)
# ---------------------------------------------------------------------------

STD_TO_VCOM = {"1993": "-93", "2002": "-2002", "2008": "-2008", "2019": "-2019"}

# Tools that use the ModelSim/Questa (vsim) non-project backend. vsim is
# expected to be on the PATH; no machine-specific launchers are referenced
# from this script so it stays portable to any machine.
MSIM_TOOLS = ("modelsim", "questa")


def _compile_lines(files: list[FileEntry], indent: str = "") -> list[str]:
    """Return the vcom/vlog compile commands for the file list.

    indent is prepended to each line so the same commands can be emitted
    inside the 'compile_all' proc body (two spaces) or at top level.
    """
    out: list[str] = []
    for entry in files:
        rel = entry.path.relative_to(REPO_ROOT).as_posix()
        if entry.path.suffix.lower() in (".vhd", ".vhdl"):
            flag = STD_TO_VCOM.get(entry.std or "2008", "-2008")
            out.append(f'{indent}vcom {flag} -work work "$repo_root/{rel}"')
        else:
            out.append(f'{indent}vlog -work work "$repo_root/{rel}"')
    return out


def write_msim_script(script_path: Path, files: list[FileEntry], top: str,
                      time_res: str | None, mode: str, tool: str,
                      manifest_name: str, ip: str, tb_label: str,
                      script_name: str) -> None:
    """Generate a flat, portable, non-project ModelSim/Questa Tcl script.

    The script is intended to be reusable on machines without Python. It may
    be run from either the IP's scripts/ or sim/ directory: it derives the
    repo root from its own location and changes into <ip>/sim/ itself, so
    all build artifacts stay in sim/.

        cd <ip>/scripts
        vsim [-c] -do <this file>
    """
    is_project = mode == "project"
    build_dir = "sim_proj" if is_project else "sim"
    cflag = "-c " if mode == "batch" else ""
    # Reconstruct the command that generates this script.
    run_cmd = f"run {ip} {manifest_name} {tool}"
    if tb_label not in (None, "", "default", "synthesis"):
        run_cmd += f" --tb {tb_label}"
    if mode != "batch":
        run_cmd += f" {mode}"
    lines = ["# ============================================================================",
             "# Generated by run.py - do not edit",
             f"# Manifest: {manifest_name}.f  Tool: {tool}  Mode: {mode}  Top: {top}",
             "#",
             f"# Create (from the fpga-ip repo root): ",
             f"#      {run_cmd}",
             "#",
             "# Run (from the fpga-ip repo root), any of:",
             f"#   1. cd {ip}/scripts",
             f"#      vsim {cflag}-do {script_name}",
             f"#   2. cd {ip}/{build_dir}",
             f"#      vsim {cflag}-do ..\\scripts\\{script_name}",
             "#",
             f"# The script changes to <ip>/{build_dir}/ itself; build artifacts go there.",
             "# ============================================================================",
             "",
             "# Locate the fpga-ip repo root (one level up from <ip>/scripts/ or",
             f"# <ip>/{build_dir}/); the guard below rejects any other launch directory.",
             "set repo_root [file normalize [file join [pwd] .. ..]]",
             "if {![file exists $repo_root/tool_capabilities.ini]} {",
             f'  puts "ERROR: run this script from <ip>/scripts/ or <ip>/{build_dir}/"',
             "  quit -code 1",
             "}",
             ""]
    # Compile step shared by both modes: define 'compile_all' once and call
    # it below, so the GUI 'recompile' helper and the batch build use the
    # exact same commands.
    lines.append("# Compile all manifest sources (std flags per file); shared")
    lines.append("# by the initial build below and the GUI recompile helper.")
    lines.append("# Named 'compile_all': 'compile' is a ModelSim-internal")
    lines.append("# command used by vcom, so it must not be shadowed.")
    lines.append("proc compile_all {} {")
    lines.append("  global repo_root")
    lines.extend(_compile_lines(files, indent="  "))
    lines.append("}")
    lines.append("")
    if is_project:
        # Project mode: native .mpf project in <ip>/sim_proj/, GUI only.
        # Mirrors the project section of common/scripts/sim_modelsim.do.
        lines.append("# Native ModelSim/Questa project mode (GUI, .mpf).")
        lines.append(f"# Build artifacts live in <ip>/{build_dir}/ (separate from the")
        lines.append("# non-project <ip>/sim/ directory).")
        lines.append("#")
        lines.append("# Environment note: clean .mpf saves require %MODELSIM% to be")
        lines.append("# cleared and a writable local modelsim.ini before vsim starts.")
        lines.append("# 'run.py ... project' sets both up; see")
        lines.append("# fpga-rules/questa_modelsim_project_guide.md.")
        lines.append("#")
        lines.append("# To reopen an already-created project after closing the GUI,")
        lines.append("# do NOT re-run this script - it rebuilds the project from")
        lines.append("# scratch (vdel/vlib work, project new). Instead open the")
        lines.append("# saved .mpf directly:")
        lines.append(f"#   1. cd {ip}/{build_dir}")
        lines.append(f'#      vsim -do "project open {ip}.mpf"')
        lines.append("#   2. or in the ModelSim/Questa GUI: File > Open > Project,")
        lines.append(f"#      select {ip}.mpf; then load the design and run:")
        lines.append(f"#      vsim work.{top}")
        lines.append("#      run -all")
        lines.append("")
        lines.append("# Change into the IP build directory, creating it on first use.")
        lines.append("set launch_dir [pwd]")
        lines.append(f"set sim_dir [file normalize [file join [pwd] ../{build_dir}]]")
        lines.append("file mkdir $sim_dir")
        lines.append("cd $sim_dir")
        lines.append("# Keep the run log in the build directory. Drop the startup")
        lines.append("# transcript vsim wrote to the launch directory, unless that")
        lines.append("# is the build directory itself.")
        lines.append("transcript file [file join $sim_dir transcript]")
        lines.append("if {![string equal $launch_dir $sim_dir]} {")
        lines.append("  catch { file delete [file join $launch_dir transcript] }")
        lines.append("}")
        lines.append("# The launcher copied a writable local modelsim.ini here; make")
        lines.append("# sure it stays writable either way.")
        lines.append("if {[file exists modelsim.ini]} {")
        lines.append("  catch { file attributes modelsim.ini -readonly 0 }")
        lines.append("}")
        lines.append("")
        lines.append("# Rebuild a fresh work library for this run.")
        lines.append("if {[file exists work]} { vdel -all work }")
        lines.append("vlib work")
        lines.append("")
        lines.append("# Compile all sources with their per-file std flags (see")
        lines.append("# 'compile_all' above); this is what actually builds work/.")
        lines.append("compile_all")
        lines.append("")
        lines.append("# Create the native ModelSim/Questa project (.mpf) from the")
        lines.append("# same sources. project new + addfile are the only reliable")
        lines.append("# way; hand-written .mpf files are rejected as corrupt.")
        lines.append(f"set proj_name {ip}")
        lines.append('set proj_file "${proj_name}.mpf"')
        lines.append("set ::simproj_file [file normalize $proj_file]")
        lines.append("project new . $proj_name")
        for entry in files:
            rel = entry.path.relative_to(REPO_ROOT).as_posix()
            lines.append(f'project addfile [file nativename [file normalize "$repo_root/{rel}"]]')
        lines.append("project close")
        lines.append("")
        lines.append("# Questa 2025.3 'project new' defaults to VHDL-2019; force the")
        lines.append("# manifest standard so the Project pane status matches the")
        lines.append("# direct compiles above.")
        lines.append("set mpf_fh [open $proj_file r]")
        lines.append("set mpf_data [read $mpf_fh]")
        lines.append("close $mpf_fh")
        lines.append("regsub -all {VHDL93 = \\d+} $mpf_data {VHDL93 = 2008} mpf_data")
        lines.append("regsub -all {vhdl_use93 \\d+} $mpf_data {vhdl_use93 2008} mpf_data")
        lines.append("set mpf_fh [open $proj_file w]")
        lines.append("puts -nonewline $mpf_fh $mpf_data")
        lines.append("close $mpf_fh")
        lines.append("")
        lines.append("# Open the project and compile through it so the Project pane")
        lines.append("# shows files as compiled (green). No simulation is loaded")
        lines.append("# yet, so the .mpf save on compileall is clean.")
        lines.append("project open [file normalize $proj_file]")
        lines.append("project compileall")
        lines.append("")
        vsim_args = ['-voptargs="+acc"']
        if time_res:
            vsim_args.append(f"-t {time_res}")
        vsim_args.append(f"work.{top}")
        lines.append(f"# Elaborate and simulate the '{top}' target.")
        lines.append("vsim " + " ".join(vsim_args))
        lines.append("")
        lines.append("# GUI: show a default wave window, then run.")
        lines.append("catch { delete wave * }")
        lines.append('add wave -divider "Default Waves"')
        lines.append(f"add wave /{top}/*")
        lines.append("catch { run -all }")
        lines.append("catch { wave zoom full }")
        lines.append("")
        lines.append("# Clean exit: unload the simulation before closing the project,")
        lines.append("# so the .mpf saves without rename noise. The 'project' wrapper")
        lines.append("# also makes GUI Compile All skip the .mpf save (-n) while a")
        lines.append("# simulation is loaded. ModelSim cannot reliably save the .mpf")
        lines.append("# while a simulation is active.")
        lines.append("catch { rename quit _simproj_real_quit }")
        lines.append("catch { rename project _simproj_real_project }")
        lines.append("proc project {args} {")
        lines.append("  set subcmd [lindex $args 0]")
        lines.append('  if {$subcmd eq "compileall" && [lsearch -exact $args "-n"] < 0} {')
        lines.append("    set args [linsert $args 1 -n]")
        lines.append("  }")
        lines.append("  uplevel 1 [linsert $args 0 _simproj_real_project]")
        lines.append("}")
        lines.append("proc quit {args} {")
        lines.append("  if {[info exists ::simproj_file]} {")
        lines.append("    catch { file attributes $::simproj_file -readonly 1 }")
        lines.append("  }")
        lines.append("  catch { _simproj_real_quit -sim }")
        lines.append("  if {[info exists ::simproj_file]} {")
        lines.append("    catch { file attributes $::simproj_file -readonly 0 }")
        lines.append("  }")
        lines.append("  catch { _simproj_real_project close }")
        lines.append("  eval _simproj_real_quit $args")
        lines.append("}")
        lines.append("")
        # Project mode produces a distinct script; write it and stop. The
        # non-project path below (recompile helper, sim/ body) is skipped.
        script_path.parent.mkdir(parents=True, exist_ok=True)
        script_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
        return
    if mode == "gui":
        lines.append("# Interactive helper (GUI): after editing a source, type")
        lines.append("# 'recompile' to rebuild and re-run.")
        lines.append("proc recompile {} {")
        lines.append("  compile_all")
        lines.append("  # Restart from time 0: reloads the design from the library,")
        lines.append("  # so recompiles take effect (no quit -sim, waves kept).")
        lines.append("  restart -f")
        lines.append("  run -all")
        lines.append("  wave zoom full")
        lines.append("}")
        lines.append("# On any uncaught error (e.g. a compile failure), print a")
        lines.append("# hint but keep the GUI open so you can fix and recompile.")
        lines.append('onerror { puts "COMPILE/ELAB ERROR - check the transcript; fix the source and type \'recompile\'" }')
        lines.append("")
    lines.append("# Change into the IP build directory, creating it on first use.")
    lines.append("set launch_dir [pwd]")
    lines.append("set sim_dir [file normalize [file join [pwd] ../sim]]")
    lines.append("file mkdir $sim_dir")
    lines.append("cd $sim_dir")
    lines.append("# Keep the run log in sim/. Drop the startup transcript vsim")
    lines.append("# wrote to the launch directory, unless that is sim/ itself.")
    lines.append("transcript file [file join $sim_dir transcript]")
    lines.append("if {![string equal $launch_dir $sim_dir]} {")
    lines.append("  catch { file delete [file join $launch_dir transcript] }")
    lines.append("}")
    lines.append("")
    if mode == "batch":
        lines.append("# Batch mode: abort and report failure on the first error.")
        lines.append("onerror {quit -code 1}")
    lines.append("# Rebuild a fresh work library for this run.")
    lines.append("if {[file exists work]} { vdel -all work }")
    lines.append("vlib work")
    lines.append("")
    lines.append("# Compile all sources (see the 'compile_all' proc above).")
    lines.append("compile_all")
    lines.append("")
    vsim_args = ['-voptargs="+acc"']
    if time_res:
        vsim_args.append(f"-t {time_res}")
    vsim_args.append(f"work.{top}")
    lines.append(f"# Elaborate and simulate the '{top}' target.")
    lines.append("vsim " + " ".join(vsim_args))
    lines.append("")
    if mode == "gui":
        lines.append("# GUI: show a default wave window, then run.")
        lines.append("catch { delete wave * }")
        lines.append('add wave -divider "Default Waves"')
        lines.append(f"add wave /{top}/*")
        lines.append("catch { run -all }")
        lines.append("catch { wave zoom full }")
    else:
        lines.append("# Batch: run to completion; exit code 0 on success.")
        lines.append("run -all")
        lines.append("quit -code 0")
    script_path.parent.mkdir(parents=True, exist_ok=True)
    script_path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def run_msim(launch_dir: Path, script_name: str, mode: str) -> int:
    """Invoke ModelSim/Questa (vsim) directly in a CMD shell.

    vsim must already be on the PATH.
    launch_dir is where vsim starts (the IP's scripts/ directory); the Tcl
    script then changes into <ip>/sim/ (or <ip>/sim_proj/ in project mode)
    itself. GUI mode runs `vsim -do <script>` (no -c): the GUI opens and
    this call blocks until the user closes it. Avoid `start /B`, whose
    empty title is mangled by the nested quoting inside `cmd /c "..."`.

    Project mode additionally copies the global %MODELSIM% ini to a writable
    local modelsim.ini in <ip>/sim_proj/ and clears %MODELSIM% for the
    child process. ModelSim/Questa cannot save the .mpf when %MODELSIM%
    points at a shared/read-only ini ("Unable to replace existing ini file
    ... Access is denied"). See fpga-rules/questa_modelsim_project_guide.md.
    """
    if mode == "batch":
        vsim_cmd = f"vsim -c -do {script_name}"
    else:
        vsim_cmd = f"vsim -do {script_name}"
    env = None
    if mode == "project":
        sim_dir = (launch_dir / ".." / "sim_proj").resolve()
        sim_dir.mkdir(parents=True, exist_ok=True)
        global_ini = os.environ.get("MODELSIM")
        if global_ini and os.path.isfile(global_ini):
            local_ini = sim_dir / "modelsim.ini"
            shutil.copyfile(global_ini, local_ini)
            try:
                os.chmod(local_ini, 0o644)  # clear any read-only attribute
            except OSError:
                pass
        env = dict(os.environ)
        env.pop("MODELSIM", None)
    inner = f"cd /d {launch_dir} & {vsim_cmd}"
    print(f"cmd : cmd.exe /c \"{inner}\"")
    return subprocess.run(["cmd.exe", "/c", inner], env=env).returncode


# ---------------------------------------------------------------------------
# Vivado XSim backend (batch/gui simulation)
# ---------------------------------------------------------------------------

# XSim compiles every VHDL source into a single 'work' library and requires
# ONE VHDL standard per library - mixing fails with "util_pkg.vdb needs to
# be re-saved since 'std.standard' changed". The backend therefore compiles
# all VHDL at the manifest DEFAULT_STD (2008 by default) rather than
# per-file std. xvhdl/xvlog/xelab/xsim must be on the PATH (Vivado env
# initialized via the v23/v25/v26 launchers in the caller's CMD shell); no
# machine-specific paths are referenced.
XSIM_STD_FLAG = {"1993": "--93", "2002": "--2002", "2008": "--2008", "2019": "--2019"}


def write_xsim_script(script_path: Path, top: str, mode: str, tool: str,
                      manifest_name: str, ip: str, tb_label: str,
                      script_name: str) -> None:
    """Generate the Vivado XSim simulation-phase Tcl script.

    XSim's Tcl entry point (`xsim <snapshot> --tclbatch <file>`) runs only
    after a snapshot exists, and its Tcl session cannot invoke the compile
    tools, so run.py orchestrates compile (xvhdl/xvlog) and elaboration
    (xelab) itself. This script covers just the run phase:

      - batch: `run -all; quit` (launched via --tclbatch).
      - gui:   default waves + `run -all`, launched via
        `xsim <snapshot> --gui --tclbatch <this file>`; the GUI stays open.

    See fpga-rules/vivado_xsim_guide.md.
    """
    run_cmd = f"run {ip} {manifest_name} {tool}"
    if tb_label not in (None, "", "default", "synthesis"):
        run_cmd += f" --tb {tb_label}"
    if mode != "batch":
        run_cmd += f" {mode}"
    snapshot = f"{top}_snapshot"
    lines = ["# ============================================================================",
             "# Generated by run.py - do not edit",
             f"# Manifest: {manifest_name}.f  Tool: {tool}  Mode: {mode}  Top: {top}",
             "#",
             f"# Create (from the fpga-ip repo root): ",
             f"#      {run_cmd}",
             "#",
             "# XSim runs the simulation phase from a snapshot produced by xelab;",
             "# its Tcl session cannot compile, so run.py does xvhdl/xvlog + xelab",
             "# and then invokes this script. See fpga-rules/vivado_xsim_guide.md.",
             "#",
             "# Batch (from the IP build directory):",
             f"#      cd {ip}/xsim",
             f"#      xsim {snapshot} --tclbatch ..\\scripts\\{script_name}",
             "#",
             "# GUI (from the IP build directory):",
             f"#      cd {ip}/xsim",
             f"#      xsim {snapshot} --gui --tclbatch ..\\scripts\\{script_name}",
             "#      (the script opens the wave window and runs -all; close the",
             "#      GUI window to exit)",
             "# ============================================================================"]
    if mode == "batch":
        lines += ["",
                  "# Batch: run to completion, then exit.",
                  "run -all",
                  "quit"]
    else:
        lines += ["",
                  "# GUI: add the top-level signals and run; the GUI stays open.",
                  f"add_wave /{top}/*",
                  "run -all"]
    script_path.parent.mkdir(parents=True, exist_ok=True)
    script_path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def run_xsim(launch_dir: Path, script_path: Path, files: list[FileEntry],
             top: str, mode: str, std: str) -> int:
    """Orchestrate the Vivado XSim flow: compile, elaborate, simulate.

    XSim's compile/elaborate tools (xvhdl/xvlog/xelab) are separate
    executables, and its Tcl entry point (--tclbatch) requires an existing
    snapshot, so the whole pipeline runs from <ip>/xsim/ here:

      1. compile every source at the single VHDL standard XSim requires;
      2. elaborate work.<top> into <top>_snapshot;
      3. batch: xsim <top>_snapshot --tclbatch <script>; gui: xsim --gui.

    Compile/elaborate commands are chained with '&&' so the first failure
    stops the run and returns its exit code.
    """
    sim_dir = (launch_dir / ".." / "xsim").resolve()
    sim_dir.mkdir(parents=True, exist_ok=True)
    # Remove stale artifacts from a previous run (compiled library,
    # snapshots, logs). The directory itself is reused, not removed.
    for name in ("xsim.dir", "xvhdl.log", "xvhdl.pb", "xvlog.log", "xvlog.pb",
                 "xelab.log", "xelab.pb", "xsim.log", "xsim.jou", "webtalk"):
        p = sim_dir / name
        if p.is_dir():
            shutil.rmtree(p, ignore_errors=True)
        else:
            try:
                p.unlink(missing_ok=True)
            except OSError:
                pass

    flag = XSIM_STD_FLAG.get(std or "2008", "--2008")
    steps = []
    for entry in files:
        if entry.path.suffix.lower() in (".vhd", ".vhdl"):
            steps.append(f"xvhdl {flag} --work work {entry.path.as_posix()}")
        else:
            steps.append(f"xvlog -sv --work work {entry.path.as_posix()}")
    # GUI needs trace information to populate the waveform window; XSim
    # otherwise errors with "compiled without trace information" when the
    # wave window loads. Batch mode runs headless, so it skips the heavier
    # -debug all elaboration.
    if mode == "gui":
        steps.append(f"xelab -debug all work.{top} -s {top}_snapshot")
    else:
        steps.append(f"xelab work.{top} -s {top}_snapshot")
    # Run from sim_dir via cwd (no 'cd /d' nesting in the cmd /c string, which
    # would break quote handling). Repo paths contain no spaces, so the tool
    # arguments need no quoting.
    build_cmd = " && ".join(steps)
    print(f"cmd : cmd.exe /c \"{build_cmd}\" (cwd: {sim_dir})")
    rc = subprocess.run(["cmd.exe", "/c", build_cmd], cwd=sim_dir).returncode
    if rc != 0:
        return rc

    if mode == "batch":
        sim_cmd = f"xsim {top}_snapshot --tclbatch {script_path.as_posix()}"
    else:
        # --gui --tclbatch: the generated script opens the wave window and
        # runs -all; the GUI stays open until the user closes it (the script
        # must not 'quit' - a scripted quit in GUI mode raises a Tcl thread
        # error on exit).
        sim_cmd = f"xsim {top}_snapshot --gui --tclbatch {script_path.as_posix()}"
    print(f"cmd : cmd.exe /c \"{sim_cmd}\" (cwd: {sim_dir})")
    return subprocess.run(["cmd.exe", "/c", sim_cmd], cwd=sim_dir).returncode


# ---------------------------------------------------------------------------
# Vivado synthesis backend (batch/gui/project)
# ---------------------------------------------------------------------------

# Target part for IP-level synthesis (matches the legacy synth_vivado.tcl
# default). Override per-run with --part; board-level projects (e.g. ZCU104)
# pass their own part number.
VIVADO_DEFAULT_PART = "xc7a35tftg256-1"


def _vivado_read_lines(files: list[FileEntry], indent: str = "") -> list[str]:
    """Return the read_vhdl/read_verilog/read_xdc commands for a closure."""
    out: list[str] = []
    for e in files:
        rel = e.path.relative_to(REPO_ROOT).as_posix()
        if e.path.suffix.lower() == ".xdc":
            out.append(f'{indent}read_xdc "$repo_root/{rel}"')
        elif e.path.suffix.lower() in (".vhd", ".vhdl"):
            flag = {"1993": "", "2019": " -vhdl2019"}.get(e.std or "2008", " -vhdl2008")
            out.append(f'{indent}read_vhdl{flag} "$repo_root/{rel}"')
        else:
            out.append(f'{indent}read_verilog -sv "$repo_root/{rel}"')
    return out


def _vivado_file_type(entry: FileEntry) -> str:
    """Map a source entry to its Vivado file_type property value."""
    if entry.path.suffix.lower() == ".sv":
        return "SystemVerilog"
    return {"1993": "VHDL", "2019": "VHDL 2019"}.get(entry.std or "2008", "VHDL 2008")


def _top_entity(files: list[FileEntry]) -> str | None:
    """Extract the top synthesis entity from the [top] section files."""
    for e in files:
        if e.section != "top":
            continue
        text = e.path.read_text(encoding="utf-8", errors="ignore")
        m = re.search(r"^\s*entity\s+(\w+)\s+is", text, re.MULTILINE)
        if m:
            return m.group(1)
    return None


def _wrap_catch_exit(body: list[str]) -> list[str]:
    """Wrap a script body so any error exits nonzero (never the Vivado% prompt)."""
    out = ["# Run the flow; on any error, report and exit nonzero so batch",
           "# mode never drops to the interactive Vivado% prompt.",
           "proc run_flow {} {",
           "  global repo_root"]
    for line in body:
        out.append(("  " + line) if line else "")
    out += ["}",
            "if {[catch {run_flow} err]} {",
            '  puts "ERROR: $err"',
            "  exit 1",
            "}",
            "exit 0"]
    return out


def _vivado_header(manifest_name: str, tool: str, mode: str, top: str,
                   run_cmd: str, ip: str, build_dir: str,
                   script_name: str) -> list[str]:
    """Shared self-locating header for the generated Vivado Tcl scripts."""
    launch_mode = "gui" if mode == "gui" else "batch"
    return ["# ============================================================================",
            "# Generated by run.py - do not edit",
            f"# Manifest: {manifest_name}.f  Tool: {tool}  Mode: {mode}  Top: {top}",
            "#",
            f"# Create (from the fpga-ip repo root): ",
            f"#      {run_cmd}",
            "#",
            "# Vivado is launched from <ip>/<build_dir>/; the script derives the",
            "# fpga-ip repo root from its launch directory (two levels up).",
            "#",
            "# Run (from the fpga-ip repo root), e.g.:",
            f"#      cd {ip}/{build_dir}",
            f"#      vivado -mode {launch_mode} -source ..\\scripts\\{script_name}",
            "# ============================================================================",
            "",
            "set repo_root [file normalize [file join [pwd] .. ..]]",
            "if {![file exists $repo_root/tool_capabilities.ini]} {",
            f'  puts "ERROR: run this script from <ip>/{build_dir}/"',
            "  exit 1",
            "}",
            ""]


def write_vivado_synth_script(script_path: Path, files: list[FileEntry],
                              top: str, part: str, tool: str,
                              manifest_name: str, ip: str,
                              script_name: str) -> None:
    """Generate a non-project Vivado batch synthesis Tcl script.

    Run headless from <ip>/vivado/ via `vivado -mode batch -source`. The
    script reads the design closure ([rtl], [top], constraints), runs
    synth_design, writes utilization/timing reports, and always exits.
    See fpga-rules/vivado_synthesis_guide.md.
    """
    run_cmd = f"run {ip} {manifest_name} {tool} batch"
    body = [f"# Non-project synthesis of '{top}' on '{part}'.",
            f"set_part {part}"]
    body += _vivado_read_lines(files)
    body += ["",
             f"synth_design -top {top} -part {part}",
             "",
             "report_utilization -file utilization.rpt",
             "report_timing -file timing.rpt"]
    lines = _vivado_header(manifest_name, tool, "batch", top, run_cmd, ip,
                           "vivado", script_name) + _wrap_catch_exit(body)
    script_path.parent.mkdir(parents=True, exist_ok=True)
    script_path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def write_vivado_gui_script(script_path: Path, files: list[FileEntry],
                            top: str, part: str, tool: str,
                            manifest_name: str, ip: str,
                            script_name: str) -> None:
    """Generate a non-project Vivado GUI Tcl script.

    Loads the design (set_part + read sources + synth_design) and leaves the
    Vivado GUI open, launched via `vivado -mode gui -source`. The design is
    synthesized in-memory; no .xpr project is created.
    """
    run_cmd = f"run {ip} {manifest_name} {tool} gui"
    lines = _vivado_header(manifest_name, tool, "gui", top, run_cmd, ip,
                           "vivado", script_name)
    lines += [f"# Non-project GUI: load '{top}' on '{part}', synthesize, and",
              "# leave the Vivado GUI open for interactive work.",
              f"set_part {part}"]
    lines.extend(_vivado_read_lines(files))
    lines += ["",
              f"synth_design -top {top} -part {part}",
              "",
              "# Do NOT exit - the Vivado GUI must stay open."]
    script_path.parent.mkdir(parents=True, exist_ok=True)
    script_path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def write_vivado_project_script(script_path: Path, files: list[FileEntry],
                                sim_files: list[FileEntry], top: str, part: str,
                                mode: str, tool: str, manifest_name: str,
                                ip: str, script_name: str) -> None:
    """Generate a native Vivado project creation Tcl script.

    Used by gui (project + open GUI) and project (headless). Design sources
    ([rtl], [top]) go to sources_1, constraints to constrs_1, and testbench
    sources ([tb:*]) to sim_1, so the project is ready for both synthesis
    and simulation. See fpga-rules/vivado_synthesis_guide.md.
    """
    proj_name = f"{top}_proj"
    run_cmd = f"run {ip} {manifest_name} {tool} {mode}"
    lines = _vivado_header(manifest_name, tool, mode, top, run_cmd, ip,
                           "vivado_proj", script_name)
    body = [f"# Create the native Vivado project '{proj_name}' on '{part}'.",
            f"create_project -force {proj_name} ./{proj_name} -part {part}",
            "",
            "# Design sources ([rtl], [top]) into sources_1."]
    for e in files:
        if e.path.suffix.lower() == ".xdc":
            continue  # constraints handled below
        rel = e.path.relative_to(REPO_ROOT).as_posix()
        body.append(f'set f [add_files -norecurse -fileset sources_1 "$repo_root/{rel}"]')
        body.append(f'set_property file_type "{_vivado_file_type(e)}" $f')
    xdcs = [e for e in files if e.path.suffix.lower() == ".xdc"]
    if xdcs:
        body += ["",
                 "# Constraints ([constraints:*]) into constrs_1.",
                 'set cf [get_filesets -quiet constrs_1]',
                 'if {$cf eq ""} { set cf [create_fileset -constrset constrs_1] }']
        for e in xdcs:
            rel = e.path.relative_to(REPO_ROOT).as_posix()
            body.append(f'add_files -norecurse -fileset constrs_1 "$repo_root/{rel}"')
    if sim_files:
        body += ["",
                 "# Simulation sources ([tb:*]) into sim_1 (testbenches).",
                 'set sf [get_filesets -quiet sim_1]',
                 'if {$sf eq ""} { set sf [create_fileset -simset sim_1] }']
        for e in sim_files:
            rel = e.path.relative_to(REPO_ROOT).as_posix()
            body.append(f'set f [add_files -norecurse -fileset sim_1 "$repo_root/{rel}"]')
            body.append(f'set_property file_type "{_vivado_file_type(e)}" $f')
    body += ["",
             f"set_property top {top} [get_filesets sources_1]",
             "# Save the project to disk.",
             "close_project"]
    lines += _wrap_catch_exit(body)
    script_path.parent.mkdir(parents=True, exist_ok=True)
    script_path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def run_vivado(build_dir: Path, script_path: Path, mode: str,
               proj_dir: Path | None) -> int:
    """Run the Vivado synthesis/project flow from a dedicated build dir.

    batch:   non-project synthesis, headless (vivado -mode batch).
    gui:     non-project GUI - the script loads the design and the Vivado
             GUI stays open (vivado -mode gui -source).
    project: creates the native .xpr project, then opens it in the GUI.

    The build directory is reset (removed + recreated) first. vivado must be
    on the PATH (Vivado env initialized via v23/v25/v26 in the caller's CMD
    shell); no machine-specific paths are referenced.
    """
    shutil.rmtree(build_dir, ignore_errors=True)
    build_dir.mkdir(parents=True, exist_ok=True)
    if mode == "gui":
        # Non-project GUI: -mode gui runs the script and keeps the GUI open.
        cmd = f"vivado -mode gui -source {script_path.as_posix()}"
        print(f"cmd : cmd.exe /c \"{cmd}\" (cwd: {build_dir})")
        return subprocess.run(["cmd.exe", "/c", cmd], cwd=build_dir).returncode
    # batch / project: run headless first (synthesis or project creation).
    cmd = f"vivado -mode batch -source {script_path.as_posix()}"
    print(f"cmd : cmd.exe /c \"{cmd}\" (cwd: {build_dir})")
    rc = subprocess.run(["cmd.exe", "/c", cmd], cwd=build_dir).returncode
    if rc != 0 or mode == "batch":
        return rc
    # project: open the created .xpr in the Vivado GUI (blocks until closed).
    if proj_dir is not None:
        xpr = proj_dir / f"{proj_dir.name}.xpr"
        if not xpr.is_file():
            print(f"ERROR: project file not found: {xpr}", file=sys.stderr)
            return 1
        cmd = f"vivado {xpr.as_posix()}"
        print(f"cmd : cmd.exe /c \"{cmd}\" (cwd: {build_dir})")
        return subprocess.run(["cmd.exe", "/c", cmd], cwd=build_dir).returncode
    return 0


def report_sim_result(mode: str, rc: int) -> int:
    """Print the result line for a target; return exit-code delta.

    Batch mode maps rc to PASS (0) / FAIL (nonzero). GUI/project modes report
    that the GUI was launched and never fail the run.
    """
    if mode == "batch":
        if rc == 0:
            print(f"{GREEN}result   : PASS{RESET}")
            return 0
        print(f"{RED}result   : FAIL (exit {rc}){RESET}")
        return 1
    print("result   : GUI launched")
    return 0


def cmd_clean(argv: list[str]) -> int:
    """Subcommand: remove build artifacts for an IP.

    Usage: run.py clean <ip>

    Deletes <ip>/sim/ (non-project build: work library, transcripts, wave
    logs), <ip>/sim_proj/ (project-mode build: the same plus the .mpf
    project), <ip>/xsim/ (XSim build: xsim.dir and logs), <ip>/vivado/
    (batch synthesis), and <ip>/vivado_proj/ (Vivado project mode). A
    directory held open by a running tool is reported and left in place.
    """
    p = argparse.ArgumentParser(
        prog="run clean",
        description="Remove an IP's build artifacts (sim/, sim_proj/, xsim/, vivado/, vivado_proj/)",
    )
    p.add_argument("ip", help="IP directory under the repo root")
    args = p.parse_args(argv)

    removed = []
    for name in ("sim", "sim_proj", "xsim", "vivado", "vivado_proj"):
        build_dir = REPO_ROOT / args.ip / name
        if not build_dir.exists():
            continue
        try:
            shutil.rmtree(build_dir)
        except PermissionError:
            print(f"ERROR: build directory is locked by a running tool "
                  f"({build_dir}); close the tool and retry.", file=sys.stderr)
            return 2
        removed.append(build_dir.relative_to(REPO_ROOT).as_posix())
    if not removed:
        print(f"nothing to clean: no build dirs under {args.ip}/")
        return 0
    print("removed build artifacts: " + ", ".join(removed))
    return 0


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def build_arg_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        prog="run",
        description="fpga-ip manifest runner",
        epilog=(
            "examples:\n"
            "  run axis_fifo vhdl modelsim gui\n"
            "  run axis_fifo vhdl modelsim project\n"
            "  run axis_fifo vhdl modelsim --tb default\n"
            "  run axis_fifo vhdl xsim batch\n"
            "  run axis_fifo vhdl xsim gui\n"
            "  run axis_fifo vhdl vivado batch\n"
            "  run axis_fifo vhdl vivado gui\n"
            "  run axis_fifo vhdl vivado project\n"
            "  run clean axis_fifo"
        ),
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    p.add_argument("ip", help="IP directory under the repo root")
    p.add_argument("manifest", help="manifest name (vhdl or vhdl.f)")
    p.add_argument("tool", help="tool profile name (modelsim, questa, vivado, xsim)")
    p.add_argument("--tb", dest="tb", default=None,
                   help="testbench name, or 'all'")
    p.add_argument("--part", default=None,
                   help=f"Vivado target part (default: {VIVADO_DEFAULT_PART})")
    p.add_argument("--version", default=None, help="optional tool version override")
    p.add_argument("--edition", default=None, help="optional tool edition override")
    p.add_argument("mode", nargs="?", default="batch",
                   help="batch (default), gui, or project")
    return p


def main(argv: list[str] | None = None) -> int:
    argv = list(sys.argv[1:] if argv is None else argv)
    if argv and argv[0] == "clean":
        return cmd_clean(argv[1:])
    args = build_arg_parser().parse_args(argv)

    mode = args.mode
    if mode not in VALID_MODES:
        print(f"ERROR: unknown mode '{mode}' (expected {', '.join(VALID_MODES)})", file=sys.stderr)
        return 2

    try:
        caps = Capabilities.load(INI_PATH)
    except RunnerError as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 2

    tool = args.tool
    if not caps.has_tool(tool):
        print(f"ERROR: unsupported tool '{tool}' (no profile in tool_capabilities.ini)",
              file=sys.stderr)
        return 2
    modes = caps.profile_modes(tool)
    if modes and mode not in modes:
        print(f"ERROR: mode '{mode}' not supported by '{tool}' (modes: {', '.join(modes)})",
              file=sys.stderr)
        return 2

    manifest_name = args.manifest if args.manifest.endswith(".f") else args.manifest + ".f"
    manifest_path = (REPO_ROOT / args.ip / "scripts" / manifest_name).resolve()
    try:
        manifest_path.relative_to(REPO_ROOT)
    except ValueError:
        print(f"ERROR: manifest path escapes repo root: {manifest_path}", file=sys.stderr)
        return 2

    try:
        manifest = parse_manifest(manifest_path)
    except RunnerError as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 2

    try:
        tb_names = select_testbenches(manifest, args.tb, tool)
    except RunnerError as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 2

    provided = caps.effective_features(tool, args.version, args.edition)
    manifest_cache: dict[Path, Manifest] = {manifest.path: manifest}

    exit_code = 0
    for tb_name in tb_names or [None]:
        tb_label = tb_name.removeprefix("tb:") if tb_name else "synthesis"
        sections = target_sections(manifest, tb_name)
        try:
            files = build_closure(manifest, sections, tool, manifest_cache)
        except RunnerError as exc:
            print(f"ERROR: {exc}", file=sys.stderr)
            return 2

        # Header
        print(f"target   : {args.ip} / {manifest_name} / {tool} / {tb_label} / {mode}")
        if tb_name:
            meta = manifest.sections[tb_name].meta
            requires = parse_feature_tokens(meta.get("requires", ""))
            req_names = [n for _, n in requires]
            bad = [n for n in req_names if n not in caps.allowed]
            if bad:
                print(f"ERROR: requires token(s) not in allowed_features: {', '.join(bad)}",
                      file=sys.stderr)
                return 2
            print(f"top      : {meta.get('top', '(missing)')}")
            print(f"requires : {', '.join(req_names) if req_names else '(none)'}")
        print("files (compile order):")
        missing_paths: list[Path] = []
        for entry in files:
            rel = entry.path.relative_to(REPO_ROOT).as_posix()
            opts = entry.compile_options()
            if entry.path.is_file():
                print(f"  [OK   ] [{entry.section:12}] {opts:24} {GREEN}{rel}{RESET}")
            else:
                print(f"  [MISS ] [{entry.section:12}] {opts:24} {RED}{rel}{RESET}")
                missing_paths.append(entry.path)
        print()

        ok_count = len(files) - len(missing_paths)
        if missing_paths:
            summary = (f"{GREEN}{ok_count} found{RESET}, "
                       f"{RED}{len(missing_paths)} missing{RESET}")
        else:
            summary = f"{GREEN}{len(files)} files found{RESET}"
        print(f"  summary: {summary}")

        if missing_paths:
            for p in missing_paths:
                print(f"{RED}ERROR: source file not found: {p}{RESET}", file=sys.stderr)
            return 2

        if tb_name:
            meta = manifest.sections[tb_name].meta
            req_names = [n for _, n in parse_feature_tokens(meta.get("requires", ""))]
            missing = [n for n in req_names if n not in provided]
            if missing:
                print(f"  WARNING: missing capability(ies) for '{tool}': {', '.join(missing)}")
                exit_code = 3

        # ModelSim / Questa simulation backend (non-project mode).
        if tb_name is not None and tool in MSIM_TOOLS:
            top = manifest.sections[tb_name].meta.get("top")
            if not top:
                print(f"ERROR: testbench [{tb_name}] has no 'top' metadata", file=sys.stderr)
                return 2
            time_res = manifest.sections[tb_name].meta.get("time_res")
            manifest_base = manifest_name[:-2] if manifest_name.endswith(".f") else manifest_name
            # Filename segments follow the command-line order:
            #   run <ip> <manifest> <tool> [--tb <tb>] [mode]
            # -> sim_<manifest>_<tool>_<tb>_<mode>.tcl  (synthesis omits tb).
            # Shorten common tool names in the filename (modelsim -> msim).
            tool_tag = {"modelsim": "msim"}.get(tool, tool)
            if tb_name:
                script_name = f"sim_{manifest_base}_{tool_tag}_{tb_label}_{mode}.tcl"
            else:
                script_name = f"sim_{manifest_base}_{tool_tag}_{mode}.tcl"
            script_path = REPO_ROOT / args.ip / "scripts" / script_name
            write_msim_script(script_path, files, top, time_res, mode, tool,
                              manifest_base, args.ip, tb_label, script_name)
            print(f"script   : {script_path.relative_to(REPO_ROOT).as_posix()}")
            # The generated script self-cds into <ip>/sim/ and rebuilds the
            # work library itself, so nothing is cleaned here. Use
            # 'run clean <ip>' to remove the build artifacts under <ip>/sim/.
            rc = run_msim(script_path.parent, script_name, mode)
            exit_code = report_sim_result(mode, rc) or exit_code
        # Vivado XSim simulation backend (batch/gui; no project mode).
        elif tb_name is not None and tool == "xsim":
            # XSim ships no UVVM libraries; skip testbenches whose requires
            # the xsim profile does not provide (mirrors simulate_xsim.bat).
            meta = manifest.sections[tb_name].meta
            req_names = [n for n, _ in parse_feature_tokens(meta.get("requires", ""))]
            missing = [n for n in req_names if n not in provided]
            if missing:
                print(f"  SKIP: testbench [{tb_name}] requires capabilities not "
                      f"provided by 'xsim': {', '.join(missing)}")
                continue
            top = meta.get("top")
            if not top:
                print(f"ERROR: testbench [{tb_name}] has no 'top' metadata", file=sys.stderr)
                return 2
            manifest_base = manifest_name[:-2] if manifest_name.endswith(".f") else manifest_name
            script_name = f"sim_{manifest_base}_{tool}_{tb_label}_{mode}.tcl"
            script_path = REPO_ROOT / args.ip / "scripts" / script_name
            write_xsim_script(script_path, top, mode, tool,
                              manifest_base, args.ip, tb_label, script_name)
            print(f"script   : {script_path.relative_to(REPO_ROOT).as_posix()}")
            # XSim needs one VHDL standard per work library, so all VHDL is
            # compiled at the manifest default; flag mixed-std manifests.
            std = manifest.default_std()
            vhdl_stds = {e.std or std for e in files
                         if e.path.suffix.lower() in (".vhd", ".vhdl")}
            if len(vhdl_stds) > 1:
                print(f"  NOTE: XSim compiles all VHDL at DEFAULT_STD {std} "
                      f"(one standard per work library; per-file std ignored)")
            rc = run_xsim(script_path.parent, script_path, files, top, mode, std)
            exit_code = report_sim_result(mode, rc) or exit_code
        # Vivado synthesis backend (batch/gui/project).
        elif tool == "vivado":
            if "top" not in manifest.sections:
                print("ERROR: manifest has no [top] section; synthesis requires "
                      "a top-level wrapper", file=sys.stderr)
                return 2
            top = _top_entity(files)
            if not top:
                print("ERROR: cannot determine the top entity from the [top] "
                      "section", file=sys.stderr)
                return 2
            part = args.part or VIVADO_DEFAULT_PART
            manifest_base = manifest_name[:-2] if manifest_name.endswith(".f") else manifest_name
            script_name = f"synth_{manifest_base}_{tool}_{mode}.tcl"
            script_path = REPO_ROOT / args.ip / "scripts" / script_name
            if mode in ("batch", "gui"):
                # Non-project: batch runs headless, gui loads the design and
                # leaves the Vivado GUI open. No project, no testbenches.
                if mode == "batch":
                    write_vivado_synth_script(script_path, files, top, part, tool,
                                              manifest_base, args.ip, script_name)
                else:
                    write_vivado_gui_script(script_path, files, top, part, tool,
                                            manifest_base, args.ip, script_name)
                build_dir = REPO_ROOT / args.ip / "vivado"
                proj_dir = None
            else:
                # project: native .xpr with testbench sources in sim_1, then GUI.
                tb_sections = [n for n in manifest.section_order if n.startswith("tb:")]
                sim_files: list[FileEntry] = []
                if tb_sections:
                    try:
                        sim_files = [e for e in
                                     build_closure(manifest, tb_sections, tool, manifest_cache)
                                     if e.path.is_file()]
                    except RunnerError as exc:
                        print(f"ERROR: {exc}", file=sys.stderr)
                        return 2
                write_vivado_project_script(script_path, files, sim_files, top,
                                            part, mode, tool, manifest_base,
                                            args.ip, script_name)
                build_dir = REPO_ROOT / args.ip / "vivado_proj"
                proj_dir = build_dir / f"{top}_proj"
            print(f"script   : {script_path.relative_to(REPO_ROOT).as_posix()}")
            rc = run_vivado(build_dir, script_path, mode, proj_dir)
            exit_code = report_sim_result(mode, rc) or exit_code

    return exit_code


if __name__ == "__main__":
    sys.exit(main())
