# ============================================================================
# Generated by run.py - do not edit
# Manifest: vhdl.f  Tool: modelsim  Mode: batch  Top: axis_fifo_tb
#
# Create (from the fpga-ip repo root): 
#      run axis_fifo vhdl modelsim
#
# Run (from the fpga-ip repo root), any of:
#   1. cd axis_fifo/scripts
#      vsim -c -do sim_vhdl_msim_default_batch.tcl
#   2. cd axis_fifo/sim
#      vsim -c -do ..\scripts\sim_vhdl_msim_default_batch.tcl
#
# The script changes to <ip>/sim/ itself; build artifacts go there.
# ============================================================================

# Locate the fpga-ip repo root (one level up from <ip>/scripts/ or
# <ip>/sim/); the guard below rejects any other launch directory.
set repo_root [file normalize [file join [pwd] .. ..]]
if {![file exists $repo_root/tool_capabilities.ini]} {
  puts "ERROR: run this script from <ip>/scripts/ or <ip>/sim/"
  quit -code 1
}

# Compile all manifest sources (std flags per file); shared
# by the initial build below and the GUI recompile helper.
# Named 'compile_all': 'compile' is a ModelSim-internal
# command used by vcom, so it must not be shadowed.
proc compile_all {} {
  global repo_root
  vcom -2008 -work work "$repo_root/common/rtl/util_pkg.vhd"
  vcom -93 -work work "$repo_root/axis_fifo/rtl/axis_fifo.vhd"
  vcom -2008 -work work "$repo_root/axis_fifo/tb/axis_fifo_tb_bfm_pkg.vhd"
  vcom -2008 -work work "$repo_root/axis_fifo/tb/axis_fifo_tb.vhd"
}

# Change into the IP build directory, creating it on first use.
set launch_dir [pwd]
set sim_dir [file normalize [file join [pwd] ../sim]]
file mkdir $sim_dir
cd $sim_dir
# Keep the run log in sim/. Drop the startup transcript vsim
# wrote to the launch directory, unless that is sim/ itself.
transcript file [file join $sim_dir transcript]
if {![string equal $launch_dir $sim_dir]} {
  catch { file delete [file join $launch_dir transcript] }
}

# Batch mode: abort and report failure on the first error.
onerror {quit -code 1}
# Rebuild a fresh work library for this run.
if {[file exists work]} { vdel -all work }
vlib work

# Compile all sources (see the 'compile_all' proc above).
compile_all

# Elaborate and simulate the 'axis_fifo_tb' target.
vsim -voptargs="+acc" work.axis_fifo_tb

# Batch: run to completion; exit code 0 on success.
run -all
quit -code 0
