# ============================================================================
# Generated by run.py - do not edit
# Manifest: vhdl.f  Tool: xsim  Mode: batch  Top: axis_fifo_tb
#
# Create (from the fpga-ip repo root): 
#      run axis_fifo vhdl xsim
#
# XSim runs the simulation phase from a snapshot produced by xelab;
# its Tcl session cannot compile, so run.py does xvhdl/xvlog + xelab
# and then invokes this script. See fpga-rules/vivado_xsim_guide.md.
#
# Batch (from the IP build directory):
#      cd axis_fifo/xsim
#      xsim axis_fifo_tb_snapshot --tclbatch ..\scripts\sim_vhdl_xsim_default_batch.tcl
#
# GUI (from the IP build directory):
#      cd axis_fifo/xsim
#      xsim axis_fifo_tb_snapshot --gui --tclbatch ..\scripts\sim_vhdl_xsim_default_batch.tcl
#      (the script opens the wave window and runs -all; close the
#      GUI window to exit)
# ============================================================================

# Batch: run to completion, then exit.
run -all
quit
