# ============================================================================
# Generated by run.py - do not edit
# Manifest: vhdl.f  Tool: modelsim  Mode: project  Top: axis_fifo_tb
#
# Create (from the fpga-ip repo root): 
#      run axis_fifo vhdl modelsim project
#
# Run (from the fpga-ip repo root), any of:
#   1. cd axis_fifo/scripts
#      vsim -do sim_vhdl_msim_default_project.tcl
#   2. cd axis_fifo/sim_proj
#      vsim -do ..\scripts\sim_vhdl_msim_default_project.tcl
#
# The script changes to <ip>/sim_proj/ itself; build artifacts go there.
# ============================================================================

# Locate the fpga-ip repo root (one level up from <ip>/scripts/ or
# <ip>/sim_proj/); the guard below rejects any other launch directory.
set repo_root [file normalize [file join [pwd] .. ..]]
if {![file exists $repo_root/tool_capabilities.ini]} {
  puts "ERROR: run this script from <ip>/scripts/ or <ip>/sim_proj/"
  quit -code 1
}

# Compile all manifest sources (std flags per file); shared
# by the initial build below and the GUI recompile helper.
# Named 'compile_all': 'compile' is a ModelSim-internal
# command used by vcom, so it must not be shadowed.
proc compile_all {} {
  global repo_root
  vcom -2008 -work work "$repo_root/common/rtl/util_pkg.vhd"
  vcom -93 -work work "$repo_root/axis_fifo/rtl/axis_fifo.vhd"
  vcom -2008 -work work "$repo_root/axis_fifo/tb/axis_fifo_tb_bfm_pkg.vhd"
  vcom -2008 -work work "$repo_root/axis_fifo/tb/axis_fifo_tb.vhd"
}

# Native ModelSim/Questa project mode (GUI, .mpf).
# Build artifacts live in <ip>/sim_proj/ (separate from the
# non-project <ip>/sim/ directory).
#
# Environment note: clean .mpf saves require %MODELSIM% to be
# cleared and a writable local modelsim.ini before vsim starts.
# 'run.py ... project' sets both up; see
# fpga-rules/questa_modelsim_project_guide.md.
#
# To reopen an already-created project after closing the GUI,
# do NOT re-run this script - it rebuilds the project from
# scratch (vdel/vlib work, project new). Instead open the
# saved .mpf directly:
#   1. cd axis_fifo/sim_proj
#      vsim -do "project open axis_fifo.mpf"
#   2. or in the ModelSim/Questa GUI: File > Open > Project,
#      select axis_fifo.mpf; then load the design and run:
#      vsim work.axis_fifo_tb
#      run -all

# Change into the IP build directory, creating it on first use.
set launch_dir [pwd]
set sim_dir [file normalize [file join [pwd] ../sim_proj]]
file mkdir $sim_dir
cd $sim_dir
# Keep the run log in the build directory. Drop the startup
# transcript vsim wrote to the launch directory, unless that
# is the build directory itself.
transcript file [file join $sim_dir transcript]
if {![string equal $launch_dir $sim_dir]} {
  catch { file delete [file join $launch_dir transcript] }
}
# The launcher copied a writable local modelsim.ini here; make
# sure it stays writable either way.
if {[file exists modelsim.ini]} {
  catch { file attributes modelsim.ini -readonly 0 }
}

# Rebuild a fresh work library for this run.
if {[file exists work]} { vdel -all work }
vlib work

# Compile all sources with their per-file std flags (see
# 'compile_all' above); this is what actually builds work/.
compile_all

# Create the native ModelSim/Questa project (.mpf) from the
# same sources. project new + addfile are the only reliable
# way; hand-written .mpf files are rejected as corrupt.
set proj_name axis_fifo
set proj_file "${proj_name}.mpf"
set ::simproj_file [file normalize $proj_file]
project new . $proj_name
project addfile [file nativename [file normalize "$repo_root/common/rtl/util_pkg.vhd"]]
project addfile [file nativename [file normalize "$repo_root/axis_fifo/rtl/axis_fifo.vhd"]]
project addfile [file nativename [file normalize "$repo_root/axis_fifo/tb/axis_fifo_tb_bfm_pkg.vhd"]]
project addfile [file nativename [file normalize "$repo_root/axis_fifo/tb/axis_fifo_tb.vhd"]]
project close

# Questa 2025.3 'project new' defaults to VHDL-2019; force the
# manifest standard so the Project pane status matches the
# direct compiles above.
set mpf_fh [open $proj_file r]
set mpf_data [read $mpf_fh]
close $mpf_fh
regsub -all {VHDL93 = \d+} $mpf_data {VHDL93 = 2008} mpf_data
regsub -all {vhdl_use93 \d+} $mpf_data {vhdl_use93 2008} mpf_data
set mpf_fh [open $proj_file w]
puts -nonewline $mpf_fh $mpf_data
close $mpf_fh

# Open the project and compile through it so the Project pane
# shows files as compiled (green). No simulation is loaded
# yet, so the .mpf save on compileall is clean.
project open [file normalize $proj_file]
project compileall

# Elaborate and simulate the 'axis_fifo_tb' target.
vsim -voptargs="+acc" work.axis_fifo_tb

# GUI: show a default wave window, then run.
catch { delete wave * }
add wave -divider "Default Waves"
add wave /axis_fifo_tb/*
catch { run -all }
catch { wave zoom full }

# Clean exit: unload the simulation before closing the project,
# so the .mpf saves without rename noise. The 'project' wrapper
# also makes GUI Compile All skip the .mpf save (-n) while a
# simulation is loaded. ModelSim cannot reliably save the .mpf
# while a simulation is active.
catch { rename quit _simproj_real_quit }
catch { rename project _simproj_real_project }
proc project {args} {
  set subcmd [lindex $args 0]
  if {$subcmd eq "compileall" && [lsearch -exact $args "-n"] < 0} {
    set args [linsert $args 1 -n]
  }
  uplevel 1 [linsert $args 0 _simproj_real_project]
}
proc quit {args} {
  if {[info exists ::simproj_file]} {
    catch { file attributes $::simproj_file -readonly 1 }
  }
  catch { _simproj_real_quit -sim }
  if {[info exists ::simproj_file]} {
    catch { file attributes $::simproj_file -readonly 0 }
  }
  catch { _simproj_real_project close }
  eval _simproj_real_quit $args
}

