# ============================================================================
# Generated by run.py - do not edit
# Manifest: vhdl.f  Tool: vivado  Mode: project  Top: axis_fifo_top
#
# Create (from the fpga-ip repo root): 
#      run axis_fifo vhdl vivado project
#
# Vivado is launched from <ip>/<build_dir>/; the script derives the
# fpga-ip repo root from its launch directory (two levels up).
#
# Run (from the fpga-ip repo root), e.g.:
#      cd axis_fifo/vivado_proj
#      vivado -mode batch -source ..\scripts\synth_vhdl_vivado_project.tcl
# ============================================================================

set repo_root [file normalize [file join [pwd] .. ..]]
if {![file exists $repo_root/tool_capabilities.ini]} {
  puts "ERROR: run this script from <ip>/vivado_proj/"
  exit 1
}

# Run the flow; on any error, report and exit nonzero so batch
# mode never drops to the interactive Vivado% prompt.
proc run_flow {} {
  global repo_root
  # Create the native Vivado project 'axis_fifo_top_proj' on 'xc7a35tftg256-1'.
  create_project -force axis_fifo_top_proj ./axis_fifo_top_proj -part xc7a35tftg256-1

  # Design sources ([rtl], [top]) into sources_1.
  set f [add_files -norecurse -fileset sources_1 "$repo_root/common/rtl/util_pkg.vhd"]
  set_property file_type "VHDL 2008" $f
  set f [add_files -norecurse -fileset sources_1 "$repo_root/axis_fifo/rtl/axis_fifo.vhd"]
  set_property file_type "VHDL" $f
  set f [add_files -norecurse -fileset sources_1 "$repo_root/axis_fifo/rtl/axis_fifo_top.vhd"]
  set_property file_type "VHDL 2008" $f

  # Simulation sources ([tb:*]) into sim_1 (testbenches).
  set sf [get_filesets -quiet sim_1]
  if {$sf eq ""} { set sf [create_fileset -simset sim_1] }
  set f [add_files -norecurse -fileset sim_1 "$repo_root/axis_fifo/tb/axis_fifo_tb_bfm_pkg.vhd"]
  set_property file_type "VHDL 2008" $f
  set f [add_files -norecurse -fileset sim_1 "$repo_root/axis_fifo/tb/axis_fifo_tb.vhd"]
  set_property file_type "VHDL 2008" $f

  set_property top axis_fifo_top [get_filesets sources_1]
  # Save the project to disk.
  close_project
}
if {[catch {run_flow} err]} {
  puts "ERROR: $err"
  exit 1
}
exit 0
