# ============================================================================
# Generated by run.py - do not edit
# Manifest: vhdl.f  Tool: vivado  Mode: batch  Top: axis_fifo_top
#
# Create (from the fpga-ip repo root): 
#      run axis_fifo vhdl vivado batch
#
# Vivado is launched from <ip>/<build_dir>/; the script derives the
# fpga-ip repo root from its launch directory (two levels up).
#
# Run (from the fpga-ip repo root), e.g.:
#      cd axis_fifo/vivado
#      vivado -mode batch -source ..\scripts\synth_vhdl_vivado_batch.tcl
# ============================================================================

set repo_root [file normalize [file join [pwd] .. ..]]
if {![file exists $repo_root/tool_capabilities.ini]} {
  puts "ERROR: run this script from <ip>/vivado/"
  exit 1
}

# Run the flow; on any error, report and exit nonzero so batch
# mode never drops to the interactive Vivado% prompt.
proc run_flow {} {
  global repo_root
  # Non-project synthesis of 'axis_fifo_top' on 'xc7a35tftg256-1'.
  set_part xc7a35tftg256-1
  read_vhdl -vhdl2008 "$repo_root/common/rtl/util_pkg.vhd"
  read_vhdl "$repo_root/axis_fifo/rtl/axis_fifo.vhd"
  read_vhdl -vhdl2008 "$repo_root/axis_fifo/rtl/axis_fifo_top.vhd"

  synth_design -top axis_fifo_top -part xc7a35tftg256-1

  report_utilization -file utilization.rpt
  report_timing -file timing.rpt
}
if {[catch {run_flow} err]} {
  puts "ERROR: $err"
  exit 1
}
exit 0
