# ============================================================================
# Generated by run.py - do not edit
# Manifest: vhdl.f  Tool: vivado  Mode: gui  Top: axis_fifo_top
#
# Create (from the fpga-ip repo root): 
#      run axis_fifo vhdl vivado gui
#
# Vivado is launched from <ip>/<build_dir>/; the script derives the
# fpga-ip repo root from its launch directory (two levels up).
#
# Run (from the fpga-ip repo root), e.g.:
#      cd axis_fifo/vivado
#      vivado -mode gui -source ..\scripts\synth_vhdl_vivado_gui.tcl
# ============================================================================

set repo_root [file normalize [file join [pwd] .. ..]]
if {![file exists $repo_root/tool_capabilities.ini]} {
  puts "ERROR: run this script from <ip>/vivado/"
  exit 1
}

# Non-project GUI: load 'axis_fifo_top' on 'xc7a35tftg256-1', synthesize, and
# leave the Vivado GUI open for interactive work.
set_part xc7a35tftg256-1
read_vhdl -vhdl2008 "$repo_root/common/rtl/util_pkg.vhd"
read_vhdl "$repo_root/axis_fifo/rtl/axis_fifo.vhd"
read_vhdl -vhdl2008 "$repo_root/axis_fifo/rtl/axis_fifo_top.vhd"

synth_design -top axis_fifo_top -part xc7a35tftg256-1

# Do NOT exit - the Vivado GUI must stay open.
