-----------------------------------------------------------------------
--Filename         : axi_read_tester_top.vhd
--Description      : Top integration for an array of axi_read_tester cores.
--                 :  - GC_NUM_TESTERS x axi_read_tester, each with
--                 :    GC_NUM_CLIENTS client slices.
--                 :  - An arrayed AXI4-Lite slave interface with one fully
--                 :    independent slave per client axilite_io plus one local
--                 :    global axilite_io at the highest index, so every tester
--                 :    is directly accessible (no internal address decode).
--                 :  - A free-running global_time counter (shared).
--                 :  - A pulse_extender opens the aperture window.
--                 :  - stat_rst / err_rst are one-cycle pulses generated by
--                 :    the local axilite_io stream pushes.
--                 :  - Combined LED output: one bit per client (index 0 ..
--                 :    N_TESTERS*N_CLIENTS-1) plus the local axilite LED at
--                 :    the highest index.
--                 :
--                 : AXI4-Lite slave index: 0 .. N_TESTERS*N_CLIENTS-1 = client
--                 : axilite_io (tester t, client c -> index t*N_CLIENTS + c),
--                 : N_TESTERS*N_CLIENTS = local (global) axilite_io.  Each index
--                 : is a fully independent AXI4-Lite slave; addr[15:14] = region
--                 : and addr[6:2] = register index (as in axilite_io).
--Author           : Rune Baeverrud
--Current Revision : 1.00
--Licensing        : Zero-Clause BSD (0BSD)
-----------------------------------------------------------------------
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use work.util_pkg.all;

entity axi_read_tester_top is
  generic (
    GC_NUM_TESTERS       : positive := 4;      -- number of tester cores
    GC_NUM_CLIENTS       : positive := 4;      -- clients per tester
    GC_ADDR_WIDTH        : positive := 32;
    GC_ID_WIDTH          : positive := 4;
    GC_CLIENT_DATA_BYTES : positive := 64;
    GC_NATIVE_DATA_BYTES : positive := 16;
    GC_NATIVE_ARLEN_WIDTH : positive range 2 to 8 := 8;
    GC_MAX_BURST         : positive := 32;
    GC_CLIENT_FIFO_DEPTH : positive range 2 to positive'high := 32;
    GC_CDC_DEPTH         : positive range 2 to 1024 := 8;
    GC_SYNC_STAGES       : positive range 2 to 4 := 2;
    GC_MON_SB_DEPTH      : positive := 256;
    GC_MON_TIME_WIDTH    : positive := 48;
    GC_PULSE_LEN         : positive := 1024   -- aperture window length (cycles)
  );
  port (
    aclk : in std_logic;
    mem_aclk    : in std_logic;
    aresetn     : in std_logic;

    -- Arrayed AXI4-Lite slaves: index 0 .. N_TESTERS*N_CLIENTS-1 = client
    -- axilite_io (tester t, client c -> index t*N_CLIENTS + c), index
    -- N_TESTERS*N_CLIENTS = local (global) axilite_io.  Every index is an
    -- independent AXI4-Lite slave, so each tester is directly accessible.
    s_axi_awaddr  : in  slv_array_t(0 to GC_NUM_TESTERS*GC_NUM_CLIENTS)(15 downto 0);
    s_axi_awprot  : in  slv_array_t(0 to GC_NUM_TESTERS*GC_NUM_CLIENTS)(2 downto 0);
    s_axi_awvalid : in  std_logic_vector(0 to GC_NUM_TESTERS*GC_NUM_CLIENTS);
    s_axi_awready : out std_logic_vector(0 to GC_NUM_TESTERS*GC_NUM_CLIENTS);
    s_axi_wdata   : in  slv32_array_t(0 to GC_NUM_TESTERS*GC_NUM_CLIENTS);
    s_axi_wstrb   : in  slv_array_t(0 to GC_NUM_TESTERS*GC_NUM_CLIENTS)(3 downto 0);
    s_axi_wvalid  : in  std_logic_vector(0 to GC_NUM_TESTERS*GC_NUM_CLIENTS);
    s_axi_wready  : out std_logic_vector(0 to GC_NUM_TESTERS*GC_NUM_CLIENTS);
    s_axi_bresp   : out slv2_array_t(0 to GC_NUM_TESTERS*GC_NUM_CLIENTS);
    s_axi_bvalid  : out std_logic_vector(0 to GC_NUM_TESTERS*GC_NUM_CLIENTS);
    s_axi_bready  : in  std_logic_vector(0 to GC_NUM_TESTERS*GC_NUM_CLIENTS);
    s_axi_araddr  : in  slv_array_t(0 to GC_NUM_TESTERS*GC_NUM_CLIENTS)(15 downto 0);
    s_axi_arprot  : in  slv_array_t(0 to GC_NUM_TESTERS*GC_NUM_CLIENTS)(2 downto 0);
    s_axi_arvalid : in  std_logic_vector(0 to GC_NUM_TESTERS*GC_NUM_CLIENTS);
    s_axi_arready : out std_logic_vector(0 to GC_NUM_TESTERS*GC_NUM_CLIENTS);
    s_axi_rdata   : out slv32_array_t(0 to GC_NUM_TESTERS*GC_NUM_CLIENTS);
    s_axi_rresp   : out slv2_array_t(0 to GC_NUM_TESTERS*GC_NUM_CLIENTS);
    s_axi_rvalid  : out std_logic_vector(0 to GC_NUM_TESTERS*GC_NUM_CLIENTS);
    s_axi_rready  : in  std_logic_vector(0 to GC_NUM_TESTERS*GC_NUM_CLIENTS);

    -- Combined LEDs: 0..N_TESTERS*N_CLIENTS-1 = per-client LEDs, the
    -- highest index = local axilite LED.
    led : out std_logic_vector(0 to GC_NUM_TESTERS*GC_NUM_CLIENTS);

    -- Native AXI read masters, one per tester (arrayed)
    ar_id    : out slv_array_t(0 to GC_NUM_TESTERS-1)(GC_ID_WIDTH-1 downto 0);
    ar_addr  : out slv_array_t(0 to GC_NUM_TESTERS-1)(GC_ADDR_WIDTH-1 downto 0);
    ar_len   : out slv_array_t(0 to GC_NUM_TESTERS-1)(GC_NATIVE_ARLEN_WIDTH-1 downto 0);
    ar_size  : out slv_array_t(0 to GC_NUM_TESTERS-1)(2 downto 0);
    ar_valid : out std_logic_vector(0 to GC_NUM_TESTERS-1);
    ar_ready : in  std_logic_vector(0 to GC_NUM_TESTERS-1);
    r_id     : in  slv_array_t(0 to GC_NUM_TESTERS-1)(GC_ID_WIDTH-1 downto 0);
    r_data   : in  slv_array_t(0 to GC_NUM_TESTERS-1)(8*GC_NATIVE_DATA_BYTES-1 downto 0);
    r_resp   : in  slv2_array_t(0 to GC_NUM_TESTERS-1);
    r_last   : in  std_logic_vector(0 to GC_NUM_TESTERS-1);
    r_valid  : in  std_logic_vector(0 to GC_NUM_TESTERS-1);
    r_ready  : out std_logic_vector(0 to GC_NUM_TESTERS-1)
  );
end entity axi_read_tester_top;

architecture rtl of axi_read_tester_top is

  -- Index of the local (global) axilite_io = highest index.
  constant C_LAST_AXIL : natural := GC_NUM_TESTERS * GC_NUM_CLIENTS;

  -- Shared global time counter.
  signal time_cnt : unsigned(GC_MON_TIME_WIDTH-1 downto 0) := (others => '0');

  -- Local axilite stream pulses (one cycle) + extended aperture window.
  signal m_axis_tvalid : std_logic_vector(2 downto 0);
  signal stat_rst_p    : std_logic;
  signal err_rst_p     : std_logic;
  signal aperture_p    : std_logic;

  -- Local axilite register / stream tie-offs.
  signal local_o_data : slv32_array_t(0 to 0);
  signal local_i_data : slv32_array_t(0 to 0);
  signal local_s_axis_tdata_nc  : slv32_array_t(0 to 0);
  signal local_s_axis_tready_nc : std_logic_vector(0 downto 0);

begin

  ---------------------------------------------------------------------
  -- Local (global) axilite: LED bit, stream pulses for stat_rst / err_rst
  -- and the aperture trigger, plus a global time read.
  ---------------------------------------------------------------------
  u_local_axil : entity work.axilite_io
    generic map (
      GC_NUM_ODATA   => 1,
      GC_NUM_IDATA   => 1,
      GC_NUM_OSTREAM => 3,
      GC_NUM_ISTREAM => 1
    )
    port map (
      aclk          => aclk,
      aresetn       => aresetn,
      s_axi_awaddr  => s_axi_awaddr(C_LAST_AXIL),
      s_axi_awprot  => s_axi_awprot(C_LAST_AXIL),
      s_axi_awvalid => s_axi_awvalid(C_LAST_AXIL),
      s_axi_awready => s_axi_awready(C_LAST_AXIL),
      s_axi_wdata   => s_axi_wdata(C_LAST_AXIL),
      s_axi_wstrb   => s_axi_wstrb(C_LAST_AXIL),
      s_axi_wvalid  => s_axi_wvalid(C_LAST_AXIL),
      s_axi_wready  => s_axi_wready(C_LAST_AXIL),
      s_axi_bresp   => s_axi_bresp(C_LAST_AXIL),
      s_axi_bvalid  => s_axi_bvalid(C_LAST_AXIL),
      s_axi_bready  => s_axi_bready(C_LAST_AXIL),
      s_axi_araddr  => s_axi_araddr(C_LAST_AXIL),
      s_axi_arprot  => s_axi_arprot(C_LAST_AXIL),
      s_axi_arvalid => s_axi_arvalid(C_LAST_AXIL),
      s_axi_arready => s_axi_arready(C_LAST_AXIL),
      s_axi_rdata   => s_axi_rdata(C_LAST_AXIL),
      s_axi_rresp   => s_axi_rresp(C_LAST_AXIL),
      s_axi_rvalid  => s_axi_rvalid(C_LAST_AXIL),
      s_axi_rready  => s_axi_rready(C_LAST_AXIL),
      o_data        => local_o_data,
      i_data        => local_i_data,
      m_axis_tdata  => open,
      m_axis_tvalid => m_axis_tvalid,
      s_axis_tdata  => local_s_axis_tdata_nc,
      s_axis_tready => local_s_axis_tready_nc
    );

  local_i_data(0) <= std_logic_vector(time_cnt(31 downto 0));  -- global time snapshot
  led(C_LAST_AXIL) <= local_o_data(0)(0);                      -- local LED bit

  -- Stream pushes generate one-cycle pulses: channel 0 = stat_rst,
  -- channel 1 = err_rst, channel 2 = aperture trigger.
  stat_rst_p <= m_axis_tvalid(0);
  err_rst_p  <= m_axis_tvalid(1);

  -- Aperture window (extended pulse).
  u_pulse : entity work.pulse_extender
    generic map (GC_PULSE_LEN => GC_PULSE_LEN)
    port map (
      clk       => aclk,
      rstn      => aresetn,
      trigger   => m_axis_tvalid(2),
      pulse_out => aperture_p
    );

  ---------------------------------------------------------------------
  -- Tester cores.
  ---------------------------------------------------------------------
  gen_tester : for t in 0 to GC_NUM_TESTERS-1 generate
    constant C_NATIVE_AR_SIZE : std_logic_vector(2 downto 0) :=
      std_logic_vector(to_unsigned(log2ceil(GC_NATIVE_DATA_BYTES), 3));

    -- Per-client AXI4-Lite vectors for this tester's core.
    signal tw_awaddr  : slv_array_t(0 to GC_NUM_CLIENTS-1)(15 downto 0);
    signal tw_awprot  : slv_array_t(0 to GC_NUM_CLIENTS-1)(2 downto 0);
    signal tw_awvalid : std_logic_vector(0 to GC_NUM_CLIENTS-1);
    signal tw_awready : std_logic_vector(0 to GC_NUM_CLIENTS-1);
    signal tw_wdata   : slv32_array_t(0 to GC_NUM_CLIENTS-1);
    signal tw_wstrb   : slv_array_t(0 to GC_NUM_CLIENTS-1)(3 downto 0);
    signal tw_wvalid  : std_logic_vector(0 to GC_NUM_CLIENTS-1);
    signal tw_wready  : std_logic_vector(0 to GC_NUM_CLIENTS-1);
    signal tw_bresp   : slv2_array_t(0 to GC_NUM_CLIENTS-1);
    signal tw_bvalid  : std_logic_vector(0 to GC_NUM_CLIENTS-1);
    signal tw_bready  : std_logic_vector(0 to GC_NUM_CLIENTS-1);
    signal tw_araddr  : slv_array_t(0 to GC_NUM_CLIENTS-1)(15 downto 0);
    signal tw_arprot  : slv_array_t(0 to GC_NUM_CLIENTS-1)(2 downto 0);
    signal tw_arvalid : std_logic_vector(0 to GC_NUM_CLIENTS-1);
    signal tw_arready : std_logic_vector(0 to GC_NUM_CLIENTS-1);
    signal tw_rdata   : slv32_array_t(0 to GC_NUM_CLIENTS-1);
    signal tw_rresp   : slv2_array_t(0 to GC_NUM_CLIENTS-1);
    signal tw_rvalid  : std_logic_vector(0 to GC_NUM_CLIENTS-1);
    signal tw_rready  : std_logic_vector(0 to GC_NUM_CLIENTS-1);
    signal tw_pipeline : std_logic_vector(0 to GC_NUM_CLIENTS-1);
    signal tw_led      : std_logic_vector(0 to GC_NUM_CLIENTS-1);
  begin
    ar_size(t) <= C_NATIVE_AR_SIZE;


    -- Fan out the arrayed AXI4-Lite slave ports to this tester's per-client
    -- arrays and back.
    gen_client : for c in 0 to GC_NUM_CLIENTS-1 generate
      constant C_IDX : natural := t * GC_NUM_CLIENTS + c;
    begin
      tw_awaddr(c)  <= s_axi_awaddr(C_IDX);
      tw_awprot(c)  <= s_axi_awprot(C_IDX);
      tw_awvalid(c) <= s_axi_awvalid(C_IDX);
      s_axi_awready(C_IDX) <= tw_awready(c);
      tw_wdata(c)   <= s_axi_wdata(C_IDX);
      tw_wstrb(c)   <= s_axi_wstrb(C_IDX);
      tw_wvalid(c)  <= s_axi_wvalid(C_IDX);
      s_axi_wready(C_IDX) <= tw_wready(c);
      s_axi_bresp(C_IDX)  <= tw_bresp(c);
      s_axi_bvalid(C_IDX) <= tw_bvalid(c);
      tw_bready(c)  <= s_axi_bready(C_IDX);
      tw_araddr(c)  <= s_axi_araddr(C_IDX);
      tw_arprot(c)  <= s_axi_arprot(C_IDX);
      tw_arvalid(c) <= s_axi_arvalid(C_IDX);
      s_axi_arready(C_IDX) <= tw_arready(c);
      s_axi_rdata(C_IDX)  <= tw_rdata(c);
      s_axi_rresp(C_IDX)  <= tw_rresp(c);
      s_axi_rvalid(C_IDX) <= tw_rvalid(c);
      tw_rready(c)  <= s_axi_rready(C_IDX);
      led(C_IDX) <= tw_led(c);
    end generate;

    u_core : entity work.axi_read_tester
      generic map (
        GC_NUM_CLIENTS       => GC_NUM_CLIENTS,
        GC_ADDR_WIDTH        => GC_ADDR_WIDTH,
        GC_ID_WIDTH          => GC_ID_WIDTH,
        GC_CLIENT_DATA_BYTES => GC_CLIENT_DATA_BYTES,
        GC_NATIVE_DATA_BYTES => GC_NATIVE_DATA_BYTES,
        GC_NATIVE_ARLEN_WIDTH => GC_NATIVE_ARLEN_WIDTH,
        GC_MAX_BURST         => GC_MAX_BURST,
        GC_CLIENT_FIFO_DEPTH => GC_CLIENT_FIFO_DEPTH,
        GC_CDC_DEPTH         => GC_CDC_DEPTH,
        GC_SYNC_STAGES       => GC_SYNC_STAGES,
        GC_MON_SB_DEPTH      => GC_MON_SB_DEPTH,
        GC_MON_TIME_WIDTH    => GC_MON_TIME_WIDTH
      )
      port map (
        aclk => aclk,
        mem_aclk    => mem_aclk,
        aresetn     => aresetn,
        s_axi_awaddr  => tw_awaddr,
        s_axi_awprot  => tw_awprot,
        s_axi_awvalid => tw_awvalid,
        s_axi_awready => tw_awready,
        s_axi_wdata   => tw_wdata,
        s_axi_wstrb   => tw_wstrb,
        s_axi_wvalid  => tw_wvalid,
        s_axi_wready  => tw_wready,
        s_axi_bresp   => tw_bresp,
        s_axi_bvalid  => tw_bvalid,
        s_axi_bready  => tw_bready,
        s_axi_araddr  => tw_araddr,
        s_axi_arprot  => tw_arprot,
        s_axi_arvalid => tw_arvalid,
        s_axi_arready => tw_arready,
        s_axi_rdata   => tw_rdata,
        s_axi_rresp   => tw_rresp,
        s_axi_rvalid  => tw_rvalid,
        s_axi_rready  => tw_rready,
        pipeline_busy => tw_pipeline,
        aperture => aperture_p,
        stat_rst => stat_rst_p,
        err_rst  => err_rst_p,
        global_time => time_cnt,
        led      => tw_led,
        ar_id    => ar_id(t),
        ar_addr  => ar_addr(t),
        ar_len   => ar_len(t),
        ar_valid => ar_valid(t),
        ar_ready => ar_ready(t),
        r_id     => r_id(t),
        r_data   => r_data(t),
        r_resp   => r_resp(t),
        r_last   => r_last(t),
        r_valid  => r_valid(t),
        r_ready  => r_ready(t)
      );
  end generate gen_tester;

  ---------------------------------------------------------------------
  -- Free-running global time counter (client clock domain).
  ---------------------------------------------------------------------
  p_time : process(aclk)
  begin
    if rising_edge(aclk) then
      if aresetn = '0' then
        time_cnt <= (others => '0');
      else
        time_cnt <= time_cnt + 1;
      end if;
    end if;
  end process p_time;

end architecture rtl;
