-----------------------------------------------------------------------
--Filename         : mem_image_corner_tb.vhd
--Description      : Corner-case regression for mem_image.
--                 :
--                 : This testbench focuses on parser and address-map
--                 : cases that are easy to miss in a normal data-pattern
--                 : test:
--                 :   * invalid lines and bad checksums are ignored,
--                 :   * Intel HEX type 03/05 start records are ignored,
--                 :   * a data record can end exactly at 0xFFFF,
--                 :   * type 04 can move the next record to 0x10000,
--                 :   * GC_GAP_BYTES=0 still merges adjacent records,
--                 :   * the region merge is transitive, and
--                 :   * holes created by a transitive merge are hits.
--                 :
--                 : The fixtures are generated by:
--                 :   python tb/data/make_images.py
--Author           : Rune Baeverrud
--Licensing        : Zero-Clause BSD (0BSD)
-----------------------------------------------------------------------
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use std.textio.all;

entity mem_image_corner_tb is
  generic (
    GC_DIR : string := "axi_mem_image/tb/data/"
  );
end entity;

architecture sim of mem_image_corner_tb is

  constant C_AW : positive := 32;
  constant C_DW : positive := 64;

  signal clk      : std_logic := '0';
  signal sim_done : boolean := false;

  -- malformed_image.hex: valid data around ignored records.
  signal malformed_addr : std_logic_vector(C_AW-1 downto 0) := (others => '0');
  signal malformed_data : std_logic_vector(31 downto 0);
  signal malformed_hit  : std_logic;
  signal malformed_ready : std_logic;

  -- boundary_image.hex: the exact 0xFFFF -> 0x10000 transition.
  signal boundary_addr : std_logic_vector(C_DW-1 downto 0) := (others => '0');
  signal boundary_data : std_logic_vector(31 downto 0);
  signal boundary_hit  : std_logic;
  signal boundary_ready : std_logic;

  -- bridge_image.hex: three records whose merge is only transitive.
  signal bridge_addr : std_logic_vector(C_AW-1 downto 0) := (others => '0');
  signal bridge_data : std_logic_vector(31 downto 0);
  signal bridge_hit  : std_logic;
  signal bridge_ready : std_logic;

begin

  -- Stop the clock after the checks so a failed or successful run always
  -- terminates cleanly under both ModelSim and XSim.
  clk <= not clk after 5 ns when not sim_done else '0';

  -- The bad checksum record in this file must not contribute bytes.  The
  -- valid records at 0x0000 and 0x0008 are close enough to form one region,
  -- so the ignored record's address becomes an internal zero-filled hole.
  u_malformed : entity work.mem_image
    generic map (
      GC_DATA_BYTES   => 4,
      GC_ADDR_WIDTH   => C_AW,
      GC_FILE         => GC_DIR & "malformed_image.hex",
      GC_MAX_REGIONS  => 1,
      GC_GAP_BYTES    => 4096,
      GC_REGION_WORDS => 4,
      GC_OUTSIDE      => "poison"
    )
    port map (
      read_en => '1', addr => malformed_addr, data => malformed_data,
      hit => malformed_hit, ready => malformed_ready
    );

  -- The first data record ends at 0xFFFF.  The following type 04 record
  -- sets the upper address to one, placing its data at 0x10000.  With a
  -- zero-byte gap policy the adjacent records remain one region.
  u_boundary : entity work.mem_image
    generic map (
      GC_DATA_BYTES   => 4,
      GC_ADDR_WIDTH   => C_DW,
      GC_FILE         => GC_DIR & "boundary_image.hex",
      GC_MAX_REGIONS  => 1,
      GC_GAP_BYTES    => 0,
      GC_REGION_WORDS => 2,
      GC_OUTSIDE      => "poison"
    )
    port map (
      read_en => '1', addr => boundary_addr, data => boundary_data,
      hit => boundary_hit, ready => boundary_ready
    );

  -- The records at 0x0000 and 0x2004 do not merge directly when the gap
  -- allowance is 4096.  The record at 0x1004 bridges both ranges; the
  -- loader must repeat its merge sweep until one region remains.
  u_bridge : entity work.mem_image
    generic map (
      GC_DATA_BYTES   => 4,
      GC_ADDR_WIDTH   => C_AW,
      GC_FILE         => GC_DIR & "bridge_image.hex",
      GC_MAX_REGIONS  => 3,
      GC_GAP_BYTES    => 4096,
      GC_REGION_WORDS => 2050,
      GC_OUTSIDE      => "poison"
    )
    port map (
      read_en => '1', addr => bridge_addr, data => bridge_data,
      hit => bridge_hit, ready => bridge_ready
    );

  p_stim : process

    procedure note(text : string) is
      variable line_buffer : line;
    begin
      write(line_buffer, string'(text));
      writeline(output, line_buffer);
    end procedure;

  begin
    wait until rising_edge(clk);
    assert malformed_ready = '1' and boundary_ready = '1' and
           bridge_ready = '1'
      report "mem_image_corner_tb: an image did not become ready"
      severity failure;

    -- ---------------------------------------------------------------
    -- Bad-record behavior
    -- ---------------------------------------------------------------
    malformed_addr <= x"00000000";
    wait until rising_edge(clk);
    assert malformed_hit = '1' and malformed_data = x"40302010"
      report "corner: valid record before bad record was not loaded"
      severity failure;

    malformed_addr <= x"00000004";
    wait until rising_edge(clk);
    assert malformed_hit = '1' and malformed_data = x"00000000"
      report "corner: bad-checksum record did not become an internal hole"
      severity failure;

    malformed_addr <= x"00000008";
    wait until rising_edge(clk);
    assert malformed_hit = '1' and malformed_data = x"83828180"
      report "corner: valid record after bad record was not loaded"
      severity failure;
    note("corner: malformed records and ignored start records checked");

    -- ---------------------------------------------------------------
    -- Exact 64 KiB boundary and 64-bit address port
    -- ---------------------------------------------------------------
    boundary_addr <= x"000000000000FFFC";
    wait until rising_edge(clk);
    assert boundary_hit = '1' and boundary_data = x"44332211"
      report "corner: data ending at 0xFFFF was not loaded"
      severity failure;

    boundary_addr <= x"0000000000010000";
    wait until rising_edge(clk);
    assert boundary_hit = '1' and boundary_data = x"88776655"
      report "corner: type 04 data at 0x10000 was not loaded"
      severity failure;

    boundary_addr <= x"0000000000010004";
    wait until rising_edge(clk);
    assert boundary_hit = '0' and boundary_data = x"DEADBEEF"
      report "corner: address immediately after the boundary image must miss"
      severity failure;
    note("corner: exact 64 KiB transition and 64-bit address width checked");

    -- ---------------------------------------------------------------
    -- Transitive merge behavior
    -- ---------------------------------------------------------------
    bridge_addr <= x"00000000";
    wait until rising_edge(clk);
    assert bridge_hit = '1' and bridge_data = x"A3A2A1A0"
      report "corner: first bridge record was not loaded"
      severity failure;

    bridge_addr <= x"00001000";
    wait until rising_edge(clk);
    assert bridge_hit = '1' and bridge_data = x"00000000"
      report "corner: transitive merged hole must be a hit"
      severity failure;

    bridge_addr <= x"00001004";
    wait until rising_edge(clk);
    assert bridge_hit = '1' and bridge_data = x"B3B2B1B0"
      report "corner: middle bridge record was not loaded"
      severity failure;

    bridge_addr <= x"00002000";
    wait until rising_edge(clk);
    assert bridge_hit = '1' and bridge_data = x"00000000"
      report "corner: second transitive merged hole must be a hit"
      severity failure;

    bridge_addr <= x"00002004";
    wait until rising_edge(clk);
    assert bridge_hit = '1' and bridge_data = x"C3C2C1C0"
      report "corner: final bridge record was not loaded"
      severity failure;

    bridge_addr <= x"00002008";
    wait until rising_edge(clk);
    assert bridge_hit = '0' and bridge_data = x"DEADBEEF"
      report "corner: address after merged extent must miss"
      severity failure;
    note("corner: transitive region merge and internal holes checked");

    report "mem_image_corner_tb: ALL CORNER CHECKS PASSED" severity note;
    sim_done <= true;
    wait;
  end process;

end architecture;
